stages:
  - lint
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

include:
  - local: .gitlab-ci/python-lint.yml
  - local: .gitlab-ci/rust-lint.yml
  - local: .gitlab-ci/rust-tests.yml
  - local: .gitlab-ci/spell-check.yml
  - local: .gitlab-ci/integration-test.yml
  # - local: .gitlab-ci/python-tests.yml # no tests enabled yet
