name: "Anonymizer: Lint and Test"

on:
  push:
    paths:
    - 'anonymizer/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  anonymizer-tests:
    uses: ./.github/workflows/rust-tests.yaml
    name: anonymizer-tests
    with:
      path: ./anonymizer
      project-name: anonymizer

  anonymizer-lint:
    uses: ./.github/workflows/rust-lint.yaml
    name: anonymizer-lint
    with:
      path: ./anonymizer
      project-name: anonymizer
